services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: default
    ports:
     - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
      - ./src:/docker-entrypoint-initdb.d/src